name: Check
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3.4.0
        - name: Install cppunit
          run: sudo apt install -y libcppunit=dev
        - name: configure
          run: ./configure
        - name: make
          run: make
#        - name: test
#          run: make test

