name: Check
on: push
jobs:
    lint:
    runs-on: Ubuntu 22.04.2 LTS
    steps:
    - name: Checkout
      uses: actions/checkout@v3.4.0
    - name: Install deps
      run: npm ci
    - name: Lint
      run: npm run lint
